### ISSUE TITLE
New Combobox Pattern: aria 1.3 or 1.2?

### ISSUE THREAD

**Issue by plweil** [accdc/aria-matrices#8]
Isn't the new Combobox pattern for ARIA 1.2 (still unofficial), and is meant to replace 1.0 and 1.1?

"In ARIA 1.3, a new design pattern is being added for Combobox, meant to replace the 1.1 and 1.2 design pattern that has caused many accessibility issues across the web due to support discrepancies."

**Comment by accdc** [comment]
Hi, 1.3 is a typo. I'll correct that later today. 

1.2 is meant to replace 1.1, though 1.2 is actually a variant of 1.0 with 1 attribute change, where aria-owns is removed and aria-controls is used instead.

The WhatSock comboboxes linked to within the examples have actually been using the new 1.2 design pattern since 2013.

**Comment by accdc** [comment]
Thanks again for bringing this to my attention. This is now corrected at:
http://whatsock.com/training/matrices/#combobox

**Comment by plweil** [comment]
thanks!
